Repository AY2021S1-CS2113T-F14-3/tp, pull requests merged in 2020-11, with the labels that each got.

#183 PED changes
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/parser/DescFavParser.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/logic/parser/RouteParser.java
Labels: priority.High, type.Bug

#188 Refactor output to Ui class
  src/main/java/seedu/duke/logic/commands/buscommand/BusCommand.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.Low, type.Task

#186 DG update /dine and /dineinfo sequence diagram
  docs/DG_Diagrams/ClearFavSequence.png
  docs/DG_Diagrams/ClearFavSequence.puml
  docs/DG_Diagrams/DineInfoSequence.png
  docs/DG_Diagrams/DineInfoSequence.puml
  docs/DG_Diagrams/DineSequence.png
  docs/DG_Diagrams/DineSequence.puml
  docs/DG_Diagrams/FacultySequence.png
  docs/DG_Diagrams/FacultySequence.puml
  docs/DG_Diagrams/ListFavSequence.png
  docs/DG_Diagrams/ListFavSequence.puml
  docs/DeveloperGuide.md
Labels: type.Documentation

#191 Addition of frequency initialisation message and comprehensive corrupted file handling
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/storage/FavStorage.java
  src/main/java/seedu/duke/storage/FreqStorage.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Bug

#193 Dg bus command seq diagram
  docs/DG_Diagrams/BusCommand/BusCommand.png
  docs/DG_Diagrams/BusCommand/BusCommand.puml
  docs/DG_Diagrams/BusCommand/getBustStop.png
  docs/DG_Diagrams/BusCommand/getBustStop.puml
  docs/DG_Diagrams/ExecFavCommand.png
  docs/DG_Diagrams/ExecFavCommand/ExecFavCommand.png
  docs/DG_Diagrams/ExecFavCommand/ExecFavCommand.puml
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/logic/commands/buscommand/BusCommand.java
  src/main/java/seedu/duke/model/bus/BusData.java
  src/test/java/seedu/duke/model/bus/BusDataTest.java
Labels: priority.High, type.Documentation

#194 Amendment of descriptions of bus stops
  src/main/java/seedu/duke/model/bus/BusStops.java
Labels: priority.Medium, severity.Low

#185 Add isValid checks
  src/main/java/seedu/duke/logic/commands/buscommand/ListStopsCommand.java
  src/main/java/seedu/duke/logic/commands/commons/ExitCommand.java
  src/main/java/seedu/duke/logic/commands/commons/HelpCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/AddFavCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
Labels: priority.High, type.Bug

#195 Update DG (class diagrams), food data and route parser
  docs/DG_Diagrams/LogicComponent.png
  docs/DG_Diagrams/LogicComponent.puml
  docs/DG_Diagrams/ModelComponent.png
  docs/DG_Diagrams/ModelComponent.puml
  docs/DG_Diagrams/RouteCommandClass.png
  docs/DG_Diagrams/RouteCommandClass.puml
  docs/DG_Diagrams/StorageComponent.png
  docs/DG_Diagrams/StorageComponent.puml
  docs/DG_Diagrams/UiComponent.png
  docs/DG_Diagrams/UiComponent.puml
  docs/DG_Diagrams/descFavClass.png
  docs/DG_Diagrams/descFavClass.puml
  src/main/java/seedu/duke/logic/parser/RouteParser.java
  src/main/java/seedu/duke/model/foodoptions/FoodPlacesData.java
Labels: priority.High, type.Bug, type.Documentation

#196 Execfav bus is valid
  src/main/java/seedu/duke/logic/commands/buscommand/BusCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/ExecFavCommand.java
Labels: priority.High, type.Bug

#198 Adding Java doc comments
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/logic/commands/buscommand/RouteMapCommand.java
  src/main/java/seedu/duke/model/bus/BusData.java
  src/main/java/seedu/duke/model/bus/BusStops.java
  src/main/java/seedu/duke/storage/FreqStorage.java
Labels: priority.Medium, type.Documentation

#200 FreqStorageTest
  docs/DG_Diagrams/RouteMapCommandSeq.png
  docs/DG_Diagrams/RouteMapCommandSeq.puml
  src/main/java/seedu/duke/storage/FreqStorage.java
  src/test/StorageTestCases/InvalidFreqList_CorruptedData
  src/test/StorageTestCases/InvalidFreqList_MissingEntry
  src/test/StorageTestCases/ValidFreqList
  src/test/java/seedu/duke/storage/FreqStorageTest.java
Labels: priority.Medium, type.JUnitTest

#202 Wamika ppp
  docs/DG_Diagrams/Architecture/Architecture.png
  docs/DG_Diagrams/Architecture/Architecture.puml
  docs/DG_Diagrams/Components/LogicComponent.png
  docs/DG_Diagrams/Components/LogicComponent.puml
  docs/DG_Diagrams/Components/ModelComponent.png
  docs/DG_Diagrams/Components/ModelComponent.puml
  docs/DG_Diagrams/Components/StorageComponent.png
  docs/DG_Diagrams/Components/StorageComponent.puml
  docs/DG_Diagrams/Components/UiComponent.png
  docs/DG_Diagrams/Components/UiComponent.puml
  docs/DG_Diagrams/DescFavCommand/descFav.png
  docs/DG_Diagrams/DescFavCommand/descFav.puml
  docs/DG_Diagrams/DescFavCommand/descFavClass.png
  docs/DG_Diagrams/DescFavCommand/descFavClass.puml
  docs/DG_Diagrams/DescFavCommand/descFavInternal.png
  docs/DG_Diagrams/DescFavCommand/descFavInternal.puml
  docs/DG_Diagrams/RouteCommand/BusData.png
  docs/DG_Diagrams/RouteCommand/BusData.puml
  docs/DG_Diagrams/RouteCommand/RouteCommand.png
  docs/DG_Diagrams/RouteCommand/RouteCommand.puml
  docs/DG_Diagrams/RouteCommand/RouteCommandClass.png
  docs/DG_Diagrams/RouteCommand/RouteCommandClass.puml
  docs/DG_Diagrams/RouteCommand/RouteCommandInternal.png
  docs/DG_Diagrams/RouteCommand/RouteCommandInternal.puml
  docs/DeveloperGuide.md
  docs/team/wamikamalik.md
Labels: priority.High, type.Documentation

#201 More error handling
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/buscommand/BusCommand.java
  src/main/java/seedu/duke/logic/commands/buscommand/RouteCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/ExecFavCommand.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Bug

#203 DG update
  docs/DG_Diagrams/AddFavSequence.png
  docs/DG_Diagrams/AddFavSequence.puml
  docs/DG_Diagrams/ListStopsSequence.png
  docs/DG_Diagrams/ListStopsSequence.puml
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#204 More JUnit
  src/main/java/seedu/duke/logic/similaritycheck/SimilarityCheck.java
  src/test/java/seedu/duke/logic/commands/buscommand/RouteCommandTest.java
  src/test/java/seedu/duke/logic/commands/favcommand/DescFavCommandTest.java
  src/test/java/seedu/duke/logic/parser/DescFavParserTest.java
  src/test/java/seedu/duke/logic/parser/RouteParserTest.java
  src/test/java/seedu/duke/logic/similaritycheck/SimilarityCheckTest.java
  src/test/java/seedu/duke/model/bus/BusTest.java
  src/test/java/seedu/duke/model/favorite/FavListTest.java
Labels: priority.High, type.JUnitTest

#206 Add PPP and JUnit
  docs/team/shuyi.md
  src/main/java/seedu/duke/logic/commands/dinecommand/DineCommand.java
  src/main/java/seedu/duke/logic/commands/dinecommand/DineInfoCommand.java
  src/test/java/seedu/duke/logic/commands/dinecommand/DineCommandTest.java
  src/test/java/seedu/duke/logic/commands/dinecommand/DineInfoCommandTest.java
  src/test/java/seedu/duke/logic/commands/favcommand/ListFavCommandTest.java
  src/test/java/seedu/duke/logic/parser/ParserTest.java
Labels: type.Documentation, type.JUnitTest

#205 Add PPP
  docs/DeveloperGuide.md
  docs/team/wuyuxin.md
  src/main/java/seedu/duke/logic/commands/favcommand/AddFavCommand.java
  src/main/java/seedu/duke/model/bus/BusStops.java
  src/main/java/seedu/duke/model/favorite/Fav.java
  src/main/java/seedu/duke/model/favorite/FavList.java
  src/test/java/seedu/duke/logic/parser/ParserTest.java
Labels: priority.High, type.Documentation, type.JUnitTest

#209 Dg ug updates and ppp
  docs/DG_Diagrams/BusCommand/getBusStop.png
  docs/DG_Diagrams/BusCommand/getBusStop.puml
  docs/DG_Diagrams/BusCommand/getBustStop.png
  docs/DeveloperGuide.md
  docs/UG_Figures/execfav3.png
  docs/UG_Figures/execfav4.png
  docs/UserGuide.md
  docs/team/EthanWong2212.md
Labels: priority.High, type.Documentation

#207 Java doc
  src/main/java/seedu/duke/logic/commands/buscommand/RouteCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/DescFavCommand.java
  src/main/java/seedu/duke/logic/parser/DescFavParser.java
  src/main/java/seedu/duke/logic/parser/RouteParser.java
  src/main/java/seedu/duke/logic/similaritycheck/SimilarityCheck.java
  src/main/java/seedu/duke/model/bus/Bus.java
  src/main/java/seedu/duke/model/bus/BusData.java
  src/main/java/seedu/duke/model/favorite/FavList.java
Labels: priority.High, type.Documentation

#212 Additional junit tests
  docs/DG_Diagrams/BusCommand/BusCommand.png
  docs/DG_Diagrams/BusCommand/BusCommand.puml
  docs/DG_Diagrams/BusCommand/getBusStop.png
  docs/DG_Diagrams/BusCommand/getBusStop.puml
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/logic/commands/buscommand/BusCommand.java
  src/main/java/seedu/duke/model/bus/BusStops.java
  src/test/StorageTestCases/FavStorageTestTXT/CorruptedFavStorage.txt
  src/test/StorageTestCases/FavStorageTestTXT/ValidFavStorage.txt
  src/test/java/seedu/duke/logic/commands/buscommand/BusCommandTest.java
  src/test/java/seedu/duke/logic/commands/favcommand/ExecFavCommandTest.java
  src/test/java/seedu/duke/storage/FavStorageTest.java
Labels: priority.Medium, type.JUnitTest

#208 Design consideration and similarity checks
  docs/DG_Diagrams/DescFavCommand/descFavInternal.png
  docs/DG_Diagrams/DescFavCommand/descFavInternal.puml
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#210 PPP - Johnson Yee
  docs/team/johnsonYee.md
Labels: priority.High, type.Documentation

#214 Manual testing structure
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#213 Amendment of route map command in DG and addition of delete fav and search freq in DG
  docs/DG_Diagrams/DeleteFavCommand/DeleteFavSeq.png
  docs/DG_Diagrams/DeleteFavCommand/DeleteFavSeq.puml
  docs/DG_Diagrams/ResetSearchFreqCommand/DisplaySearchFreq.png
  docs/DG_Diagrams/ResetSearchFreqCommand/DisplaySearchFreq.puml
  docs/DG_Diagrams/ResetSearchFreqCommand/ResetSearchFreqSeq.png
  docs/DG_Diagrams/ResetSearchFreqCommand/ResetSearchFreqSeq.puml
  docs/DG_Diagrams/RouteMapCommand/RouteMapCommand.png
  docs/DG_Diagrams/RouteMapCommand/RouteMapCommand.puml
  docs/DG_Diagrams/RouteMapCommand/RouteMapCommandClass.png
  docs/DG_Diagrams/RouteMapCommand/RouteMapCommandOverallSeq.png
  docs/DG_Diagrams/RouteMapCommand/RouteMapCommandOverallSeq.puml
  docs/DG_Diagrams/RouteMapCommand/RouteMapCommandSeq.png
  docs/DG_Diagrams/RouteMapCommand/RouteMapCommandSeq.puml
  docs/DG_Diagrams/RouteMapCommandSeq.png
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/logic/commands/buscommand/RouteMapCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/DeleteFavCommand.java
  src/main/java/seedu/duke/model/bus/BusData.java
  src/main/java/seedu/duke/model/bus/BusStops.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Documentation

#217 Re-name PPP to fit naming scheme
  docs/AboutUs.md
  docs/team/johnson-yee.md
  docs/team/mrwsy1.md
Labels: priority.High, type.Documentation

#216 Reordering of UG and correcting spelling error in DG
  docs/DG_Diagrams/RouteMapCommand/RouteMapCommand.png
  docs/DG_Diagrams/RouteMapCommand/RouteMapCommand.puml
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#218 Freq Reset Test case and amendment of delete fav exception message
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/favcommand/DeleteFavCommand.java
  src/test/StorageTestCases/FreqStorageTestCases/InvalidFreqList_CorruptedData
  src/test/StorageTestCases/FreqStorageTestCases/InvalidFreqList_MissingEntry
  src/test/StorageTestCases/FreqStorageTestCases/ValidFreqList
  src/test/java/seedu/duke/logic/commands/buscommand/ResetSearchFreqCommandTest.java
  src/test/java/seedu/duke/storage/FreqStorageTest.java
Labels: priority.Medium, type.JUnitTest

#224 Manual testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/wamikamalik.md
Labels: priority.High, type.Documentation

#221 Addition of manual testing and more javadoc
  docs/DeveloperGuide.md
  docs/team/johnson-yee.md
  src/main/java/seedu/duke/logic/commands/buscommand/ResetSearchFreqCommand.java
  src/main/java/seedu/duke/logic/commands/buscommand/RouteMapCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/DeleteFavCommand.java
Labels: priority.Medium, type.Documentation

#228 Fix negative number bug for descfav
  src/main/java/seedu/duke/model/favorite/FavList.java
Labels: priority.High, type.Bug

#219 Add manual testing for DG
  docs/DeveloperGuide.md
  docs/team/mrwsy1.md
  src/main/java/seedu/duke/logic/commands/dinecommand/DineCommand.java
  src/main/java/seedu/duke/logic/commands/dinecommand/DineInfoCommand.java
  src/main/java/seedu/duke/model/favorite/FavList.java
Labels: type.Documentation

#230 update PPP
  docs/team/johnson-yee.md
Labels: type.Documentation

#231 Minor edits to ppp
  docs/team/johnson-yee.md
Labels: type.Documentation

#220 Manual testing and javadocs addition
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/logic/commands/buscommand/BusCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/ExecFavCommand.java
  src/main/java/seedu/duke/logic/parser/ExecFavParser.java
  src/main/java/seedu/duke/model/bus/BusData.java
  src/main/java/seedu/duke/storage/FavStorage.java
Labels: priority.Medium, type.Documentation

#232 Addition of more javadoc comment and refactoring of methods
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/logic/commands/favcommand/DeleteFavCommand.java
  src/main/java/seedu/duke/storage/FreqStorage.java
Labels: priority.Medium, type.Documentation

#223 Fix bug and update test
  src/main/java/seedu/duke/storage/FavStorage.java
  src/test/StorageTestCases/FavStorageTestTXT/CorruptedFavStorage.txt
  src/test/java/seedu/duke/storage/FavStorageTest.java
Labels: priority.High, type.Bug

#234 Update note in UG
  docs/UserGuide.md
  docs/_config.yml
Labels: priority.High, type.Documentation

#236 Minor UG changes and exception
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/parser/DescFavParser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/logic/commands/buscommand/BusCommandTest.java
  src/test/java/seedu/duke/logic/commands/buscommand/RouteCommandTest.java
  src/test/java/seedu/duke/logic/parser/DescFavParserTest.java
Labels: priority.High, type.Documentation

#237 Update for UG DG and some Javadoc
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/model/favorite/FavList.java
Labels: priority.High, type.Documentation

#238 Added search freq and intro to cli
  docs/UG_Figures/appleCLI.png
  docs/UG_Figures/displayfreq.png
  docs/UserGuide.md
  docs/team/johnson-yee.md
Labels: priority.Low, type.Documentation

#240 Update ppp and dg
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/ethanwong2212.md
Labels: priority.Medium, type.Documentation

#241 update DG to fit reposense
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#242 Update ug and ppp
  docs/UG_Figures/execfav3.png
  docs/UG_Figures/execfav4.png
  docs/UserGuide.md
  docs/team/ethanwong2212.md
Labels: priority.Medium, type.Documentation

#243 Update toc
  docs/DeveloperGuide.md
Labels: type.Documentation

#244 Moved help into common features
  docs/UG_Figures/Nav@NUSstartScreen.png
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#245 Update ug diagram
  docs/UG_Figures/Nav@NUSstartScreen.png
Labels: priority.Low, type.Documentation

#247 Add remove whitespace in between words in addfav command
  src/main/java/seedu/duke/logic/commands/favcommand/AddFavCommand.java
  src/test/java/seedu/duke/logic/commands/favcommand/AddFavCommandTest.java
Labels: priority.High, type.Bug

#249 changes to UG - images and formatting
  docs/UG_Figures/addfav1.png
  docs/UG_Figures/addfav2.png
  docs/UG_Figures/clearfav1.png
  docs/UG_Figures/deleteFavExample.png
  docs/UG_Figures/descfavinput.PNG
  docs/UG_Figures/dine2.png
  docs/UG_Figures/dineinfo3.png
  docs/UG_Figures/execfav1.png
  docs/UG_Figures/execfav2.png
  docs/UG_Figures/execfav3.png
  docs/UG_Figures/execfav4.png
  docs/UG_Figures/faculty1.png
  docs/UG_Figures/freq1.png
  docs/UG_Figures/help1.png
  docs/UG_Figures/listfav1.png
  docs/UG_Figures/routeInput1.png
  docs/UG_Figures/routeshort1.png
  docs/UG_Figures/routeshort2.png
  docs/UG_Figures/routeshort3.png
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#250 Fix blunder
  docs/UG_Figures/displayfreq.png
  docs/UG_Figures/freq1.png
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#252 Addition of storage of favourite commands and faq question
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#251 Fix grammar
  docs/UserGuide.md
Labels: priority.High, type.Documentation
