Repository AY2021S1-CS2113T-F14-3/tp, pull requests merged in 2020-10, with the labels that each got.

#28 Addition of BusStops enum and listStops command.
  src/main/java/seedu/duke/Bus.java
  src/main/java/seedu/duke/BusStops.java
  src/main/java/seedu/duke/Duke.java
Labels: priority.High, type.Task

#26 Basic route command
  src/main/java/seedu/duke/Bus.java
  src/main/java/seedu/duke/BusData.java
  src/main/java/seedu/duke/BusStops.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/logic/commands/RouteCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/logic/parser/RouteParser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Task

#29 Add command class for /allbus
  src/main/java/seedu/duke/Bus.java
  src/main/java/seedu/duke/BusData.java
  src/main/java/seedu/duke/BusStops.java
  src/main/java/seedu/duke/logic/commands/AllBusCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Task

#19 Addition of RouteMapCommands class
  src/main/java/seedu/duke/Bus.java
  src/main/java/seedu/duke/BusData.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/logic/commands/Command.java
  src/main/java/seedu/duke/logic/commands/ExitCommand.java
  src/main/java/seedu/duke/logic/commands/RouteMapCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Task

#33 JUnit tests for Route command
  src/test/java/seedu/duke/BusDataTest.java
  src/test/java/seedu/duke/BusTest.java
  src/test/java/seedu/duke/logic/commands/RouteCommandTest.java
  src/test/java/seedu/duke/logic/parser/ParserTest.java
  src/test/java/seedu/duke/logic/parser/RouteParserTest.java
Labels: priority.High, type.JUnitTest

#37 Implement busCommand class for running of /bus command
  src/main/java/seedu/duke/BusData.java
  src/main/java/seedu/duke/BusStops.java
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/BusCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
Labels: priority.High, type.Task

#39 Add some JUnit tests for BusData class
  src/main/java/seedu/duke/BusStops.java
  src/test/java/seedu/duke/BusDataTest.java
Labels: priority.High, type.JUnitTest

#35 Assertions and logging
  build.gradle
  logger.log
  logger.log.lck
  src/main/java/seedu/duke/Bus.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/logic/commands/HelpCommand.java
  src/main/java/seedu/duke/logic/commands/RouteCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/logic/parser/RouteParser.java
Labels: priority.High, type.Task

#43 Addition of user guide
  docs/README.md
  docs/UserGuide.md
  logger.log.1
  logger.log.2
  src/main/java/seedu/duke/BusStops.java
Labels: priority.Medium, type.Documentation

#50 Addition of exception handling and assertion into RouteMapCommand
  src/main/java/seedu/duke/BusData.java
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/RouteMapCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/logic/commands/RouteMapCommandTest.java
Labels: priority.Medium, type.JUnitTest

#57 Food places data
  src/main/java/seedu/duke/BusData.java
  src/main/java/seedu/duke/DiningOptions.java
  src/main/java/seedu/duke/FoodPlace.java
  src/main/java/seedu/duke/FoodPlacesData.java
Labels: priority.High, type.Task

#63 Storage abstract class and FavStorage class
  logger.log
  logger.log.1
  logger.log.2
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/storage/FavStorage.java
  src/main/java/seedu/duke/storage/Storage.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#68 Dg
  .gitignore
  docs/Architecture.png
  docs/Architecture.puml
  docs/DeveloperGuide.md
  docs/RouteCommandClass.png
  docs/RouteCommandClass.puml
  logger.log
  logger.log.1
  logger.log.1.lck
Labels: priority.High, type.Documentation

#72 Removal of nested user inputs to facillitate fast typing
  logger.log.1
  logger.log.1.lck
  logger.log.2.lck
  logger.log.3
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/RouteMapCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/logic/commands/RouteMapCommandTest.java
  src/test/java/seedu/duke/logic/parser/ParserTest.java
Labels: priority.High, type.JUnitTest, type.Task

#69 Update busStops.java to include more functions
  data/FavList.txt
  src/main/java/seedu/duke/BusStops.java
Labels: priority.High, type.Task

#74 Add /dine and /dineinfo features
  .gitignore
  src/main/java/seedu/duke/DiningOptions.java
  src/main/java/seedu/duke/FoodPlace.java
  src/main/java/seedu/duke/FoodPlacesData.java
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/DineCommand.java
  src/main/java/seedu/duke/logic/commands/DineInfoCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High

#73 Similarity check
  .gitignore
  logger.log.2
  src/main/java/seedu/duke/logic/SimilarityCheck.java
  src/main/java/seedu/duke/logic/commands/BusCommand.java
  src/main/java/seedu/duke/logic/commands/RouteCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/logic/SimilarityCheckTest.java
Labels: priority.High, type.Enhancement, type.Task

#75 Ug
  docs/RouteCommandClass.png
  docs/RouteCommandClass.puml
  docs/UG_Figures/routeInput1.png
  docs/UG_Figures/routeOutput1.png
  docs/UG_Figures/routeOutput2.png
  docs/UG_Figures/routeOutput3.png
  docs/UserGuide.md
  src/main/java/seedu/duke/Bus.java
Labels: priority.High, type.Documentation

#79 Resize images
  docs/UserGuide.md
Labels: type.Documentation

#80 Ug
  docs/UG_Figures/similarOutput1.png
  docs/UG_Figures/similarOutput2.png
  docs/UserGuide.md
Labels: type.Documentation

#78 Addition of search frequency to enhance user experience
  .gitignore
  data/FavList.txt
  logger.log.3
  src/main/java/seedu/duke/BusData.java
  src/main/java/seedu/duke/BusInfo.java
  src/main/java/seedu/duke/BusStops.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/BusCommand.java
  src/main/java/seedu/duke/logic/commands/ResetSearchFreqCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/storage/FreqStorage.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#84 UG /bus command feature
  docs/UG_Figures/bus1.png
  docs/UG_Figures/bus2.png
  docs/UG_Figures/bus3.png
  docs/UG_Figures/bus4.png
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#81 Amendment to introduction and routemap feature in user guide
  docs/UG_Figures/routemap1.png
  docs/UG_Figures/routemap3.png
  docs/UG_Figures/routemap4.png
  docs/UserGuide.md
Labels: priority.High, type.Task

#85 Update UG with /dine and /dineinfo
  docs/UG_Figures/dine1.png
  docs/UG_Figures/dineinfo1.png
  docs/UserGuide.md
Labels: priority.High

#87 Addition of reset function into user guide
  docs/UG_Figures/freq1.png
  docs/UserGuide.md
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Documentation

#89 Slight amendments to UG file
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#83 basic skeleton for DG draft
  docs/DeveloperGuide.md
  docs/LogicComponent.png
  docs/LogicComponent.puml
  docs/UiComponent.png
  docs/UiComponent.puml
Labels: type.Documentation

#91 Addition of target user profile and value proposition to developers' guide
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#92 Fav skeleton
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/favorite/Fav.java
  src/main/java/seedu/duke/favorite/FavList.java
  src/main/java/seedu/duke/logic/commands/favcommand/AddFavCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/DeleteFavCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/DescFavCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/ExecFavCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/ListFavCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/storage/FavStorage.java
  src/main/java/seedu/duke/storage/Storage.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#95 Descfav command
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/FoodPlacesData.java
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/favorite/Fav.java
  src/main/java/seedu/duke/favorite/FavList.java
  src/main/java/seedu/duke/logic/commands/favcommand/DescFavCommand.java
  src/main/java/seedu/duke/logic/parser/DescFavParser.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/logic/parser/RouteParser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Story

#82 Add favourite function
  .gitignore
  logger.log.1
  logger.log.1.lck
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/favcommand/AddFavCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/model/favorite/Fav.java
  src/main/java/seedu/duke/model/favorite/FavList.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Task

#100 Add listfav and clearfav
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/favcommand/ClearFavCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/ListFavCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/model/favorite/Fav.java
  src/main/java/seedu/duke/model/favorite/FavList.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High

#103 Addition of DeleteFavCommand function
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/favorite/FavList.java
  src/main/java/seedu/duke/logic/commands/favcommand/DeleteFavCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/test/java/seedu/duke/model/bus/BusDataTest.java
Labels: priority.High, type.Task

#107 Addition of main features table into user guide
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#104 Descfav JUnit
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/favorite/FavList.java
  src/main/java/seedu/duke/logic/commands/favcommand/DeleteFavCommand.java
  src/main/java/seedu/duke/logic/parser/DescFavParser.java
  src/main/java/seedu/duke/model/favorite/FavList.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/logic/parser/DescFavParserTest.java
  src/test/java/seedu/duke/model/favorite/FavListTest.java
Labels: priority.High, type.JUnitTest

#111 DG format and route command
  docs/DG_Diagrams/Architecture.png
  docs/DG_Diagrams/Architecture.puml
  docs/DG_Diagrams/BusData.png
  docs/DG_Diagrams/BusData.puml
  docs/DG_Diagrams/LogicComponent.png
  docs/DG_Diagrams/LogicComponent.puml
  docs/DG_Diagrams/RouteCommand.png
  docs/DG_Diagrams/RouteCommand.puml
  docs/DG_Diagrams/RouteCommandClass.png
  docs/DG_Diagrams/RouteCommandClass.puml
  docs/DG_Diagrams/RouteCommandInternal.png
  docs/DG_Diagrams/RouteCommandInternal.puml
  docs/DG_Diagrams/UiComponent.png
  docs/DG_Diagrams/UiComponent.puml
  docs/DeveloperGuide.md
  docs/LogicComponent.png
  docs/UiComponent.png
Labels: priority.High, type.Documentation

#109 JUnit tests for /addfav function
  src/test/java/seedu/duke/logic/commands/favcommand/AddFavCommandTest.java
  src/test/java/seedu/duke/model/favorite/FavListTest.java
  src/test/java/seedu/duke/model/favorite/FavTest.java
Labels: priority.High, type.JUnitTest

#99 Fav execfav
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/favcommand/ExecFavCommand.java
  src/main/java/seedu/duke/logic/parser/ExecFavParser.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/model/favorite/FavList.java
Labels: priority.High, type.Task

#112 DG descfav command
  docs/DG_Diagrams/LogicComponent.png
  docs/DG_Diagrams/LogicComponent.puml
  docs/DG_Diagrams/ModelComponent.png
  docs/DG_Diagrams/ModelComponent.puml
  docs/DG_Diagrams/RouteCommandClass.png
  docs/DG_Diagrams/RouteCommandClass.puml
  docs/DG_Diagrams/StorageComponent.png
  docs/DG_Diagrams/StorageComponent.puml
  docs/DG_Diagrams/descFav.png
  docs/DG_Diagrams/descFav.puml
  docs/DG_Diagrams/descFavClass.png
  docs/DG_Diagrams/descFavClass.puml
  docs/DG_Diagrams/descFavInternal.png
  docs/DG_Diagrams/descFavInternal.puml
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#114 DG dine sequence diagram
  docs/DG_Diagrams/DineSequence.png
  docs/DG_Diagrams/DineSequence.puml
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#113 DG addfav sequence diagram
  docs/DG_Diagrams/AddFavSequence.png
  docs/DG_Diagrams/AddFavSequence.puml
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#117 Update headers
  docs/DeveloperGuide.md
Labels: type.Documentation

#118 Fix header sequence DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#119 Update diagrams
  docs/DG_Diagrams/RouteCommand.png
  docs/DG_Diagrams/RouteCommand.puml
  docs/DG_Diagrams/RouteCommandInternal.png
  docs/DG_Diagrams/RouteCommandInternal.puml
  docs/DG_Diagrams/descFavInternal.png
  docs/DG_Diagrams/descFavInternal.puml
Labels: priority.High, type.Documentation

#115 DG exec fav command sequence diagram
  docs/DG_Diagrams/ExecFavCommand.png
  docs/DG_Diagrams/ExecFavCommand.puml
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/logic/parser/ExecFavParser.java
Labels: priority.High, type.Documentation

#116 Addition of sequence diagram for RouteMapCommand in DG
  docs/DG_Diagrams/Nav@NUSLogo.jpg
  docs/DG_Diagrams/RouteMapCommand.puml
  docs/DG_Diagrams/RouteMapCommandClass.png
  docs/DG_Diagrams/RouteMapCommandSeq.png
  docs/DG_Diagrams/RouteMapCommandSeq.puml
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#122 Fav skeleton
  docs/UG_Figures/help1.png
  docs/UserGuide.md
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Documentation

#130 Fixes for bugs identified
  docs/DG_Diagrams/AddFavSequence.puml
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/favcommand/AddFavCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/model/favorite/Fav.java
Labels: priority.High, type.Bug

#132 Fix activation bar error and removal of exception throwing in sequence diagram
  docs/DG_Diagrams/RouteMapCommandSeq.png
  docs/DG_Diagrams/RouteMapCommandSeq.puml
Labels: priority.High, type.Documentation

#136 /descfav command for UG
  docs/UG_Figures/afterdescfav.png
  docs/UG_Figures/beforedescfav.PNG
  docs/UG_Figures/descfavinput.PNG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#137 Update command summary for descfav
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#143 Execfav command ug
  docs/UG_Figures/execfav1.png
  docs/UG_Figures/execfav2.png
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#145 Update UG
  docs/DG_Diagrams/DineInfoSequence.png
  docs/DG_Diagrams/DineInfoSequence.puml
  docs/DG_Diagrams/DineSequence.png
  docs/DG_Diagrams/DineSequence.puml
  docs/UG_Figures/clearfav1.png
  docs/UG_Figures/dineinfo2.png
  docs/UG_Figures/dineinfo3.png
  docs/UG_Figures/listfav1.png
  docs/UG_Figures/listfav2.png
  docs/UserGuide.md
Labels: type.Documentation

#144 Exec fav command testing
  src/main/java/seedu/duke/logic/commands/favcommand/ExecFavCommand.java
  src/main/java/seedu/duke/logic/parser/ExecFavParser.java
  src/main/java/seedu/duke/model/favorite/FavList.java
  src/test/java/seedu/duke/logic/commands/favcommand/ExecFavCommandTest.java
Labels: priority.Medium, type.JUnitTest

#142 Addition of purpose of UG, amendment of introduction and quick start
  docs/UG_Figures/Nav@NUSLogo.jpg
  docs/UG_Figures/Nav@NUSstartScreen.png
  docs/UG_Figures/windowsCLI.png
  docs/UG_Figures/windowsPath.png
  docs/UserGuide.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/favcommand/DeleteFavCommand.java
  src/main/java/seedu/duke/storage/FreqStorage.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.Medium, type.Documentation

#147 Addition of example for deleteFav example
  docs/UG_Figures/deleteFavExample.png
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#148 UG for addfav
  docs/UG_Figures/addfav1.png
  docs/UG_Figures/addfav2.png
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#178 [PE dryrun fix] Update /dine feature and Add /faculty feature
  docs/UG_Figures/dine2.png
  docs/UG_Figures/faculty1.png
  docs/UG_Figures/help1.png
  docs/UserGuide.md
  src/main/java/seedu/duke/logic/commands/dinecommand/DineCommand.java
  src/main/java/seedu/duke/logic/commands/dinecommand/FacultyCommand.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/model/foodoptions/FoodPlace.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Documentation, type.Enhancement

#179 Ped changes
  src/main/java/seedu/duke/exceptions/ExceptionType.java
  src/main/java/seedu/duke/logic/commands/buscommand/RouteCommand.java
  src/main/java/seedu/duke/logic/commands/commons/Command.java
  src/main/java/seedu/duke/logic/commands/favcommand/DescFavCommand.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Bug, type.Task

#180 Handle corrupted data favlist.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/logic/commands/buscommand/BusCommand.java
  src/main/java/seedu/duke/storage/FavStorage.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Bug

#182 Add isValid parameter
  src/main/java/seedu/duke/logic/commands/buscommand/AllBusCommand.java
  src/main/java/seedu/duke/logic/commands/dinecommand/DineCommand.java
  src/main/java/seedu/duke/logic/commands/dinecommand/DineInfoCommand.java
  src/main/java/seedu/duke/logic/commands/dinecommand/FacultyCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/ClearFavCommand.java
  src/main/java/seedu/duke/logic/commands/favcommand/ListFavCommand.java
Labels: priority.Medium, type.Enhancement
